language: node_js

node_js:
  - stable

before_install:
  - npm install -g @lhci/cli

install:
  - npm install
  - npm install --save-dev codecov

script:
  - npm run build
  - npm test
  - ./node_modules/.bin/codecov --token="b89b8db6-bcb1-4dc0-b9ab-544b1c3af011"

after_success:
  - lhci autorun --rc-overrides.upload.target=temporary-public-storage

addons:
  chrome: stable
